### ISSUE TITLE
大神能出个简易的readme文档吗，实在不会用？

### ISSUE THREAD

**Issue by xuelingzhizun** [onethingpcs/onecloud-app#2]
大神能出个简易的readme文档吗，实在不会用？

十分感谢你的付出

**Comment by hzexe** [comment]
还没到你折腾的时候,项目死掉之前或许会开源的.

**Comment by onethingpcs** [comment]
早期玩客币时候作弊成绩用的，签名代码在，链克死了，公开出来啦
https://github.com/onethingpcs/onecloud-app/blob/master/app/miner.plugin-minion.ipk/bin/minion/src/base/__init__.py#L286
